Migration
MapColonies/catalog-upload-service pull request #3
Opened 2020-12-17 12:20 UTC by cl-shaharshavit-rnd

2020-12-17 20:05 UTC, asafMasa requested changes
great job, and you are missing a lot of logs

2020-12-17 20:05 UTC, asafMasa commented on src/multer/storage/fileStstemStorageBuilder.ts
> +  private createUploadFolder(
add a row space

2020-12-20 06:39 UTC, cl-shaharshavit-rnd commented on confd/production.tmpl
> +    "imageIndexerBaseUrl": "{{ getv "/configuration/dependentServices/imageIndexerBaseUrl" "http://localhost:3001/images" }}",
we use to to check if the file exists to block create request that will override data and update requests with missing data

2020-12-20 06:41 UTC, cl-shaharshavit-rnd commented on src/containerConfig.ts
> +      storage = new FileSystemStorageBuilder(logger).createStorage();
linter wont let me create variables in switch case

2020-12-20 06:41 UTC, cl-shaharshavit-rnd commented on src/containerConfig.ts
> +      storage = new S3StorageBuilder(logger).createStorage();
linter wont let me create variables in switch case

2020-12-20 06:42 UTC, cl-shaharshavit-rnd commented on src/models/createUploadRequest.ts
> +  additionalData: ImageMetadata;
that was the definitions when we made the service.
it should be changed to match current epic but it shouldn't be part of this PR

2020-12-20 06:46 UTC, cl-shaharshavit-rnd commented on src/services/catalogDbService.ts
> +      this.logger.debug(`trace: ${error.stack as string}`);
look at the log levels

2020-12-20 06:46 UTC, cl-shaharshavit-rnd commented on src/services/catalogDbService.ts
> +      this.logger.error(`exsists request to ${url} failed: ${error.message}`);
look at the log levels

2020-12-20 06:47 UTC, cl-shaharshavit-rnd commented on src/multer/storage/fileStstemStorageBuilder.ts
> +export class FileSystemStorageBuilder {
rename to what?

2020-12-20 06:49 UTC, cl-shaharshavit-rnd commented on src/multer/storage/fileStstemStorageBuilder.ts
> +import * as multer from 'multer';
didn't try this time but when we created the original version this it didn't work with any other way  (something with the typescript compilation)

2020-12-20 06:53 UTC, cl-shaharshavit-rnd commented on src/multer/storage/fileStstemStorageBuilder.ts
> +  private createUploadFolder(
fixed

2020-12-20 09:15 UTC, asafMasa commented on src/containerConfig.ts
> +      storage = new FileSystemStorageBuilder(logger).createStorage();
as discussed

2020-12-20 09:15 UTC, asafMasa commented on src/containerConfig.ts
> +      storage = new S3StorageBuilder(logger).createStorage();
as discussed

2020-12-20 09:16 UTC, asafMasa commented on src/models/createUploadRequest.ts
> +  additionalData: ImageMetadata;
ok, open an issue on this and then we will resolve this comment

2020-12-20 09:42 UTC, asafMasa requested changes

2020-12-20 09:42 UTC, asafMasa commented on src/multer/storage/fileStstemStorageBuilder.ts
> +export class FileSystemStorageBuilder {
as discussed

2020-12-20 09:46 UTC, cl-shaharshavit-rnd commented on src/models/createUploadRequest.ts
> +  additionalData: ImageMetadata;
https://github.com/MapColonies/catalog-upload-service/issues/5

2020-12-20 09:47 UTC, asafMasa approved these changes

2020-12-20 09:53 UTC, merged